services:
  web:
    container_name: nextjs-app-dev
    build:
      context: ..
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLL_INTERVAL: "1000"
    env_file:
      - ../.env.local
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ../:/app:cached
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    entrypoint: ["/bin/bash", "/app/docker/dev-entrypoint.sh"]
    stdin_open: true
    tty: true

volumes:
  node_modules:
  next_cache:
